name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download SDL2
        uses: albin-johansson/download-sdl2@v0.1-alpha.2
        with:
          version: 2.0.14
          sources_destination: ./SDL2
          binaries_destination: ./bin